# Generated by Django 4.1.5 on 2023-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
